-- M39.x — Character creation: forbidden names moderation list
-- Réserve modération + PNJ : `Editeur d'univers/lune-noire-data-v19.json` (persons[].name).
-- Jetons alignés sur CharacterCreateHandler : ASCII alphanum + underscore, longueur 3–32 ; variantes
-- sans accents, formes compactes et avec underscores ; titres : retrait des (…), découpe sur « / ».

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

START TRANSACTION;

CREATE TABLE IF NOT EXISTS forbidden_character_names (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_forbidden_character_names_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO forbidden_character_names (name) VALUES
  ('admin'),
  ('administrateur'),
  ('administrator'),
  ('admins'),
  ('archange_gabriel'),
  ('archangegabriel'),
  ('argon'),
  ('atride'),
  ('baron_d_hurkel'),
  ('barondhurkel'),
  ('console'),
  ('dame_parsifal'),
  ('dameparsifal'),
  ('desdemone'),
  ('dev'),
  ('developer'),
  ('developpeur'),
  ('dharix'),
  ('dracchennauknh'),
  ('drakkahen'),
  ('duc_d_ornan'),
  ('duc_ushker'),
  ('ducdornan'),
  ('ducushker'),
  ('enchanteur'),
  ('enchanteur_de_haazheel'),
  ('enchanteurdehaazheel'),
  ('enfant_parsifal'),
  ('enfantparsifal'),
  ('epouse'),
  ('esmeralda'),
  ('favorite_de_l_empereur'),
  ('favoritedelempereur'),
  ('feidreiva'),
  ('fey'),
  ('feydriva'),
  ('fifi'),
  ('frater_sinister'),
  ('fratersinister'),
  ('fratus_sinister'),
  ('fratussinister'),
  ('game_master'),
  ('gamemaster'),
  ('garundel'),
  ('george_d_horkher'),
  ('georgedhorkher'),
  ('ghorghor_bey'),
  ('ghorghorbey'),
  ('gm'),
  ('godefroy'),
  ('goum'),
  ('grand_pretre_de_la_lune_noire'),
  ('grandpretredelalunenoire'),
  ('gunther'),
  ('haazheel'),
  ('haazheel_thorn'),
  ('haazheelthorn'),
  ('haghendorf'),
  ('haut_drakkhen'),
  ('hautdrakkhen'),
  ('hellaynnea'),
  ('hizin'),
  ('hokhosi'),
  ('hubert'),
  ('iaun_reith'),
  ('iaunreith'),
  ('intendant_wis'),
  ('intendantwis'),
  ('kruikna'),
  ('l_echo_d_haazheel_thorn'),
  ('l_emissaire_de_haazheel'),
  ('l_empereur_de_lhynn'),
  ('l_enfant_imperial'),
  ('l_imperatrice'),
  ('l_oracle'),
  ('la_chasseresse'),
  ('la_faucheuse'),
  ('la_princesse_elfique'),
  ('la_succube'),
  ('lachasseresse'),
  ('lafaucheuse'),
  ('laprincesseelfique'),
  ('lasuccube'),
  ('lcdlln'),
  ('le_baron'),
  ('le_chevalier_errant'),
  ('le_commandeur_roux'),
  ('le_geant_dzorak'),
  ('le_grand_maitre_lion'),
  ('le_grand_prince'),
  ('le_haut_tharque'),
  ('le_jeune_elfe_jade'),
  ('le_mage_shamballeau'),
  ('le_magister_de_magistrya'),
  ('le_messager_lunaire'),
  ('le_prince_des_tenebres'),
  ('le_seigneur_de_kendrhi'),
  ('le_seigneur_du_jade'),
  ('le_serpent'),
  ('le_serpent_heraut_de_methrhton'),
  ('le_venerable'),
  ('le_vieux_garde'),
  ('lebaron'),
  ('lechevaliererrant'),
  ('lechodhaazheelthorn'),
  ('lecommandeurroux'),
  ('legeantdzorak'),
  ('legrandmaitrelion'),
  ('legrandprince'),
  ('lehauttharque'),
  ('lejeuneelfejade'),
  ('lemageshamballeau'),
  ('lemagisterdemagistrya'),
  ('lemessagerlunaire'),
  ('lemissairedehaazheel'),
  ('lempereurdelhynn'),
  ('lenfantimperial'),
  ('leprincedestenebres'),
  ('leseigneurdekendrhi'),
  ('leseigneurdujade'),
  ('leserpent'),
  ('leserpentherautdemethrhton'),
  ('levenerable'),
  ('levieuxgarde'),
  ('limperatrice'),
  ('loracle'),
  ('lucifer'),
  ('maitre'),
  ('maitre_grhumpdeth'),
  ('maitre_gunthar'),
  ('maitregrhumpdeth'),
  ('maitregunthar'),
  ('master'),
  ('meldrim'),
  ('methraton'),
  ('mj'),
  ('mod'),
  ('moderator'),
  ('modo'),
  ('murata'),
  ('nasha'),
  ('nepharianne_netzharine'),
  ('nephariannenetzharine'),
  ('nerellhen'),
  ('null'),
  ('ogun_ogun'),
  ('ogunogun'),
  ('okhost'),
  ('pazuzu'),
  ('pere_de_wismerhill'),
  ('peredewismerhill'),
  ('pile_ou_face'),
  ('pileouface'),
  ('pilou'),
  ('pretre_de_la_lune_noire'),
  ('pretredelalunenoire'),
  ('pretreofficiantdelaresurrection'),
  ('prince_agnos'),
  ('prince_brakkh'),
  ('prince_draakh'),
  ('prince_parsifal'),
  ('princeagnos'),
  ('princebrakkh'),
  ('princedraakh'),
  ('princeoghinlaveugleauxmilleyeux'),
  ('princeparsifal'),
  ('root'),
  ('seigneur_balimor'),
  ('seigneur_goristroy'),
  ('seigneur_laemeth'),
  ('seigneurbalimor'),
  ('seigneurgoristroy'),
  ('seigneurgreldinardbarondemoork'),
  ('seigneurlaemeth'),
  ('selindorf'),
  ('server'),
  ('serveur'),
  ('shard'),
  ('sierhelt'),
  ('staff'),
  ('support'),
  ('supportclient'),
  ('system'),
  ('test'),
  ('tester'),
  ('undefined'),
  ('urmacht'),
  ('urmarcht'),
  ('wismerhill'),
  ('xhan'),
  ('xygga'),
  ('zharhol'),
  ('zhenner');

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
