name: Windows Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest  # ou le label de votre runner Gitea

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake --preset win64

      - name: Build
        run: cmake --build --preset win64

      - name: Smoke test (headless)
        run: .\build\engine_app.exe --app.mode=smoke --headless=1
        timeout-minutes: 1