#pragma once

#include "engine/render/FrameGraph.h"
#include "engine/render/AssetRegistry.h"
#include "engine/render/InstanceBatch.h"

#include <vulkan/vulkan_core.h>

#include <cstddef>
#include <cstdint>
#include <unordered_map>

namespace engine::render
{
	/// Geometry pass: renders opaque geometry into GBuffer (A=albedo, B=normal, C=ORM) + depth.
	/// Uses a single pipeline (VS/PS), render pass with 3 color + 1 depth attachment, depth test enabled.
	///
	/// M03.3: pipeline layout now accepts an optional material descriptor set layout (set = 0,
	/// 3 combined-image-samplers: BaseColor/Normal/ORM). If materialLayout is valid, it is
	/// included in the pipeline layout and the descriptor set is bound before each draw call.
	class GeometryPass
	{
	public:
		GeometryPass() = default;
		GeometryPass(const GeometryPass&) = delete;
		GeometryPass& operator=(const GeometryPass&) = delete;

		/// Creates render pass and pipeline.
		/// Shader SPIR-V words must remain valid until Destroy() is called.
		/// \param formatVelocity  M07.3: velocity buffer format (e.g. R16G16_SFLOAT).
		/// \param materialLayout  Optional descriptor set layout for material textures (set = 0).
		bool Init(VkDevice device, VkPhysicalDevice physicalDevice,
		          VkFormat formatA, VkFormat formatB, VkFormat formatC, VkFormat formatVelocity, VkFormat depthFormat,
		          const uint32_t* vertSpirv, size_t vertWordCount,
		          const uint32_t* fragSpirv, size_t fragWordCount,
		          VkDescriptorSetLayout materialLayout = VK_NULL_HANDLE,
		          VkPipelineCache pipelineCache = VK_NULL_HANDLE);

		/// Records the geometry pass: begin render pass, bind pipeline (and material descriptor
		/// set if provided), draw mesh at given LOD, end pass.
		/// \param lodLevel  M09.3: LOD level 0..3; mesh LOD chain used when mesh has lodLevelCount > 0.
		/// \param instanceMatrix  Optional single-object transform uploaded into the identity instance buffer.
		/// \param loadExistingGbuffer  If true (and load pass was created at Init), continues G-buffer without clearing
		///                            (use after terrain prepass). Otherwise clears as usual.
		void Record(VkDevice device, VkCommandBuffer cmd, Registry& registry, VkExtent2D extent,
		            ResourceId idA, ResourceId idB, ResourceId idC, ResourceId idVelocity, ResourceId idDepth,
		            const float* prevViewProjMat4, const float* viewProjMat4, const MeshAsset* mesh,
		            uint32_t lodLevel = 0,
		            VkDescriptorSet materialDescriptorSet = VK_NULL_HANDLE,
		            const float* instanceMatrix = nullptr,
		            uint32_t materialIndex = 0,
		            bool loadExistingGbuffer = false);

		/// M09.3: Records instanced draws for batches (mesh+material key). instanceBuffer holds mat4s at each batch's instanceBufferOffset.
		void RecordInstanced(VkDevice device, VkCommandBuffer cmd, Registry& registry, VkExtent2D extent,
		            ResourceId idA, ResourceId idB, ResourceId idC, ResourceId idVelocity, ResourceId idDepth,
		            const float* prevViewProjMat4, const float* viewProjMat4,
		            const InstanceBatch* batches, uint32_t batchCount,
		            VkBuffer instanceBuffer,
		            bool loadExistingGbuffer = false);

		/// Records indexed indirect draws generated by the GPU culling pass.
		void RecordIndirect(VkDevice device, VkCommandBuffer cmd, Registry& registry, VkExtent2D extent,
		            ResourceId idA, ResourceId idB, ResourceId idC, ResourceId idVelocity, ResourceId idDepth,
		            const float* prevViewProjMat4, const float* viewProjMat4, const MeshAsset* mesh,
		            VkBuffer indirectBuffer, uint32_t indirectDrawCount,
		            VkDescriptorSet materialDescriptorSet = VK_NULL_HANDLE,
		            const float* instanceMatrix = nullptr,
		            uint32_t materialIndex = 0,
		            bool loadExistingGbuffer = false);

		/// Releases render pass and pipeline. Safe to call when not initialized.
		void Destroy(VkDevice device);

		/// Destroys all cached framebuffers and clears the cache (e.g. on resize when FG resources are recreated).
		void InvalidateFramebufferCache(VkDevice device);

		bool IsValid() const { return m_renderPass != VK_NULL_HANDLE && m_pipeline != VK_NULL_HANDLE; }

		/// True when the optional load-op pass + pipeline exist (world editor terrain prepass).
		bool HasLoadPass() const { return m_renderPassLoad != VK_NULL_HANDLE && m_pipelineLoad != VK_NULL_HANDLE; }

		/// Returns true if this pass was initialised with a material descriptor set layout.
		bool HasMaterialLayout() const { return m_hasMaterialLayout; }

	private:
		struct FramebufferKey
		{
			VkRenderPass renderPass = VK_NULL_HANDLE;
			VkImageView  views[5]   = {};
			uint32_t     width      = 0;
			uint32_t     height     = 0;
			bool operator==(const FramebufferKey& o) const;
		};
		struct FramebufferKeyHash
		{
			size_t operator()(const FramebufferKey& k) const;
		};
		std::unordered_map<FramebufferKey, VkFramebuffer, FramebufferKeyHash> m_fbCache;

		VkRenderPass     m_renderPass        = VK_NULL_HANDLE;
		VkRenderPass     m_renderPassLoad    = VK_NULL_HANDLE;
		VkPipelineLayout m_pipelineLayout   = VK_NULL_HANDLE;
		VkPipeline       m_pipeline         = VK_NULL_HANDLE;
		VkPipeline       m_pipelineLoad      = VK_NULL_HANDLE;
		bool             m_hasMaterialLayout = false; ///< True if materialLayout was provided at Init.
		/// M09.3: identity mat4 for single-instance draw (binding 1).
		VkBuffer         m_identityInstanceBuffer = VK_NULL_HANDLE;
		VkDeviceMemory   m_identityInstanceMemory = VK_NULL_HANDLE;
	};

} // namespace engine::render
